### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'ix'

### ISSUE THREAD

**Issue by huangyongsh523** [jon-xu/scSplit#14]
looks like current scSplit using an older version of indexing using .ix instead of .loc. I got error message 
  warnings.warn(
Traceback (most recent call last):
  File "/sfs/qumulo/qhome/yh9fj/.local/lib/python3.8/site-packages/scSplit/scSplit", line 642, in <module>
    scSplit()
  File "/sfs/qumulo/qhome/yh9fj/.local/lib/python3.8/site-packages/scSplit/scSplit", line 354, in __init__
    getattr(self, args.command)()
  File "/sfs/qumulo/qhome/yh9fj/.local/lib/python3.8/site-packages/scSplit/scSplit", line 525, in run
    model.distinguishing_alleles(pos)
  File "/sfs/qumulo/qhome/yh9fj/.local/lib/python3.8/site-packages/scSplit/scSplit", line 280, in distinguishing_alleles
    alt_or_ref = alt_or_ref.ix[[x for x in alt_or_ref.index if x[0] not in ['X','Y','MT']]]
  File "/apps/software/standard/core/anaconda/2020.11-py3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'

This is my code --
python $dir_scSplit/scSplit run --r $dir_vcf/ref_filtered.csv -a $dir_vcf/alt_filtered.csv -n 2 

I have updated pandas to 1.3.3
Thanks
-Yong
yh9fj@virginia.edu

**Comment by jon-xu** [comment]
Yong,

Thanks for pointing it out! Some inconsistency in version on Pypi.

Please clone it from github before I fix it in Pypi.

Thanks,
Jon

**Comment by jon-xu** [comment]
ok, pypi is up to date as well.
Thanks again!
