### ISSUE TITLE
run command error

### ISSUE THREAD

**Issue by vjbaskar** [jon-xu/scSplit#20]
Hi,

I am using scsplit for demultiplexing scatac-seq data. I get the following error when I run `scSplit run -r ref_filt.csv -a alt_filt.csv -n 3`. My vcf file contains chr1 - chr22, chrX, chrY, and chrM. 

I am using python3.6. I do not know how to get the scsplit version but the comment in scSplit file says Aug 2018. 

Thanks
Vijay
```
Traceback (most recent call last):
  File "/rds/project/rds-SDzz0CATGms/users/vs401/soft/__venvs/anaconda3/envs/demux/lib/python3.6/site-packages/scSplit/scSplit", line 642, in <module>
    scSplit()
  File "/rds/project/rds-SDzz0CATGms/users/vs401/soft/__venvs/anaconda3/envs/demux/lib/python3.6/site-packages/scSplit/scSplit", line 354, in __init__
    getattr(self, args.command)()
  File "/rds/project/rds-SDzz0CATGms/users/vs401/soft/__venvs/anaconda3/envs/demux/lib/python3.6/site-packages/scSplit/scSplit", line 525, in run
    model.distinguishing_alleles(pos)
  File "/rds/project/rds-SDzz0CATGms/users/vs401/soft/__venvs/anaconda3/envs/demux/lib/python3.6/site-packages/scSplit/scSplit", line 280, in distinguishing_alleles
    alt_or_ref = alt_or_ref.ix[[x for x in alt_or_ref.index if x[0] not in ['X','Y','MT']]]
  File "/rds/project/bg200/rds-bg200-hphi-gottgens/users/vs401/soft/__venvs/anaconda3/envs/demux/lib/python3.6/site-packages/pandas/core/generic.py", line 5136, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'

```

**Comment by jon-xu** [comment]
Hi Vijay,

I believe you are using an old version which had a bug.
Please uninstall it and re-install with the current version.

Thanks,
Jon

**Comment by vjbaskar** [comment]
Hi Jon,
Thanks! I installed it very recently using pip. I will clone the github then.
Vijay
