### ISSUE TITLE
Error during running the scSplit

### ISSUE THREAD

**Issue by ahmadsam66** [jon-xu/scSplit#21]
Hello,

I wanted to run the scSplit and I faced with following error :

```
Traceback (most recent call last):
  File "./scSplit", line 19, in <module>
    import os, sys, io, vcf, csv, math, datetime, pickle, argparse, gzip
  File "/home/c97000131/miniconda3/lib/python3.7/site-packages/vcf/__init__.py", line 166, in <module>
    from parser import Reader, Writer
ImportError: cannot import name 'Reader' from 'parser' (/home/c97000131/miniconda3/lib/python3.7/lib-dynload/parser.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by ahmadsam66** [comment]
Solved I used conda version of PyVCF
